name: freeze
description: "Flutter PWA Platform - Share Flutter apps as instantly-runnable PWAs"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  dio: ^5.4.0

  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0

  go_router: ^13.0.0

  json_annotation: ^4.8.1

  responsive_framework: ^1.1.1

  url_launcher: ^6.2.1

  # Animation and UI enhancements
  rive: ^0.12.4
  lottie: ^3.1.0
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # JSON serialization code generation
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 200
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900
